"""Reporting: uncertainty, hyperparameter sensitivity, rank stability.

Post-processing over recorded per-problem or per-level numbers. Nothing here
executes code or touches a clock.
"""

from enamel_ext.report.hyperparams import (
    HComparison,
    attainable_range,
    compare_under_h,
    eff_at_h,
    reorderable_pairs,
    rescore_at_alpha,
)
from enamel_ext.report.levels import (
    PAPER_SLOWDOWNS,
    LevelSummary,
    describe_levels,
    level_fraction_at,
    limit_level,
    limit_level_counts,
    q_distribution,
    q_ratios,
    sensitivity_shares,
    tolerated_slowdown,
)
from enamel_ext.report.parity import (
    EFF_TOLERANCE,
    INVERSION_MARGIN,
    PASS_TOLERANCE,
    Deviation,
    Inversion,
    PairResolution,
    ParityResult,
    TauFloor,
    compare,
    deviations,
    differential_bound,
    format_parity,
    inversions,
    resolution,
    resolvable_pairs,
    tau_floor,
)
from enamel_ext.report.stats import (
    Interval,
    bootstrap_ci,
    kendall_tau,
    paired_bootstrap_diff_ci,
    paired_sign_test,
)

__all__ = [
    "EFF_TOLERANCE",
    "INVERSION_MARGIN",
    "PASS_TOLERANCE",
    "PAPER_SLOWDOWNS",
    "Deviation",
    "HComparison",
    "Interval",
    "Inversion",
    "LevelSummary",
    "PairResolution",
    "ParityResult",
    "TauFloor",
    "attainable_range",
    "bootstrap_ci",
    "compare",
    "compare_under_h",
    "describe_levels",
    "deviations",
    "differential_bound",
    "eff_at_h",
    "format_parity",
    "inversions",
    "kendall_tau",
    "level_fraction_at",
    "limit_level",
    "limit_level_counts",
    "paired_bootstrap_diff_ci",
    "paired_sign_test",
    "q_distribution",
    "q_ratios",
    "reorderable_pairs",
    "resolution",
    "resolvable_pairs",
    "rescore_at_alpha",
    "sensitivity_shares",
    "tau_floor",
    "tolerated_slowdown",
]
